### ISSUE TITLE
Deepsort class

### ISSUE THREAD

**Issue by duongnghia222** [sujanshresstha/YOLOv9_DeepSORT#1]
Can you provide the folder contain deepsort class

**Comment by sujanshresstha** [comment]
Hi @duongnghia222,
I have used python package of DeepSORT
`pip install deep-sort-realtime`

**Comment by sujanshresstha** [comment]
Hi @duongnghia222,
I've utilized the Python package DeepSORT. You can install it via pip using the following command:

`pip install deep-sort-realtime`
