### ISSUE TITLE
ISSUE WITH TRACKING BOUNDING BOX

### ISSUE THREAD

**Issue by MuhammadBilal848** [sujanshresstha/YOLOv9_DeepSORT#3]
There is a tracking issue, sometimes there is a delay in removing the bounding box even after detection disappears, the bounding box remains and takes a long to begone.
![issue](https://github.com/sujanshresstha/YOLOv9_DeepSORT/assets/57318407/a9930ef3-9bb1-4ce8-b433-efc10ffe8de7)

**Comment by sujanshresstha** [comment]
Hi, @MuhammadBilal848.
To address the issue of lingering bounding boxes even after a detection disappears, you can adjust the parameters of the DeepSort tracker to make it more responsive to changes in detections. Specifically, you can modify the max_age and n_init parameters of the DeepSort tracker initialization.
Reducing max_age will make the tracker quicker to remove tracks that no longer receive detections. Adjusting n_init can help in confirming tracks more quickly, which might also indirectly affect how fast a track is removed when detections are lost.
`tracker = DeepSort(max_age=20, n_init=3)`

**Comment by MuhammadBilal848** [comment]
Will try that. Thanks.
